spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edaily
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: onur
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
    path: /openapi/v3/api-docs
  swagger-ui:
    enabled: true
    path: /openapi/swagger-ui.html

