spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edaily
    username: onur
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
